// generated by table-mocks; DO NOT EDIT

package fake

import (
	"sync"

	"github.com/vitreuz/xtmg-ref/srv/database"
)

type Resource struct {
	appendByFilterMethod map[int]ResourceAppendByFilterMethod
	appendByFilterMutex  sync.RWMutex
	AppendByFilterCalls  int

	decodeMethod map[int]ResourceDecodeMethod
	decodeMutex  sync.RWMutex
	DecodeCalls  int
}

type ResourceAppendByFilterMethod struct {
	Data      []byte
	Filters   []database.Filter
	ErrResult error
}

type ResourceDecodeMethod struct {
	Data      []byte
	ErrResult error
}

func NewResource() *Resource {
	fake := &Resource{}
	fake.appendByFilterMethod = make(map[int]ResourceAppendByFilterMethod)
	fake.decodeMethod = make(map[int]ResourceDecodeMethod)

	return fake
}

func (fake *Resource) AppendByFilter(data []byte, filters ...database.Filter) (errResult error) {
	fake.appendByFilterMutex.Lock()
	fakeMethod := fake.appendByFilterMethod[fake.AppendByFilterCalls]
	fakeMethod.Data = data
	fakeMethod.Filters = filters
	fake.appendByFilterMethod[fake.AppendByFilterCalls] = fakeMethod
	fake.AppendByFilterCalls++
	fake.appendByFilterMutex.Unlock()

	return fakeMethod.ErrResult
}

func (fake *Resource) AppendByFilterReturns(errResult error) *Resource {
	fake.appendByFilterMutex.Lock()
	fakeMethod := fake.appendByFilterMethod[0]
	fakeMethod.ErrResult = errResult
	fake.appendByFilterMethod[0] = fakeMethod
	fake.appendByFilterMutex.Unlock()

	return fake
}

func (fake *Resource) AppendByFilterGetArgs() (data []byte, filters []database.Filter) {
	fake.appendByFilterMutex.RLock()
	data = fake.appendByFilterMethod[0].Data
	filters = fake.appendByFilterMethod[0].Filters
	fake.appendByFilterMutex.RUnlock()

	return data, filters
}

type ResourceAppendByFilterFunc func(ResourceAppendByFilterMethod) ResourceAppendByFilterMethod

func (fake *Resource) AppendByFilterForCall(call int, fns ...ResourceAppendByFilterFunc) *Resource {
	fake.appendByFilterMutex.Lock()
	for _, fn := range fns {
		fakeMethod := fake.appendByFilterMethod[call]
		fake.appendByFilterMethod[call] = fn(fakeMethod)
	}
	fake.appendByFilterMutex.Unlock()

	return fake
}

func (fake *Resource) Decode(data []byte) (errResult error) {
	fake.decodeMutex.Lock()
	fakeMethod := fake.decodeMethod[fake.DecodeCalls]
	fakeMethod.Data = data
	fake.decodeMethod[fake.DecodeCalls] = fakeMethod
	fake.DecodeCalls++
	fake.decodeMutex.Unlock()

	return fakeMethod.ErrResult
}

func (fake *Resource) DecodeReturns(errResult error) *Resource {
	fake.decodeMutex.Lock()
	fakeMethod := fake.decodeMethod[0]
	fakeMethod.ErrResult = errResult
	fake.decodeMethod[0] = fakeMethod
	fake.decodeMutex.Unlock()

	return fake
}

func (fake *Resource) DecodeGetArgs() (data []byte) {
	fake.decodeMutex.RLock()
	data = fake.decodeMethod[0].Data
	fake.decodeMutex.RUnlock()

	return data
}

type ResourceDecodeFunc func(ResourceDecodeMethod) ResourceDecodeMethod

func (fake *Resource) DecodeForCall(call int, fns ...ResourceDecodeFunc) *Resource {
	fake.decodeMutex.Lock()
	for _, fn := range fns {
		fakeMethod := fake.decodeMethod[call]
		fake.decodeMethod[call] = fn(fakeMethod)
	}
	fake.decodeMutex.Unlock()

	return fake
}
